maximum_availability_zones: 5

encrypt: true
kms_key_alias: alias/efs

performance_mode: generalPurpose # generalPurpose | maxIO
throughput_mode: bursting # bursting | provisioned
provisioned_throughput: 0.0

ip_blocks:
  efs:
    - stack

securityGroups:
  efs:
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
      ips:
        - stack
