maximum_availability_zones: 5

# create the efs mount points
# true | false
create_mounts: true

# encrypt: true
# kms_key_alias: alias/efs
#
# performance_mode: generalPurpose # generalPurpose | maxIO
# throughput_mode: bursting # bursting | provisioned
# provisioned_throughput: 0.0
